[package]
name = "nuclear-hdf5"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
hdf5 = { package = "hdf5-metno", version = "0.10.0" }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"

[features]
local = []